# Generated by Django 2.0 on 2019-06-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20190602_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
