# Generated by Django 2.0 on 2019-06-04 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_user_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_suspended',
            field=models.IntegerField(default=0),
        ),
    ]
