# Generated by Django 2.0 on 2019-06-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_auto_20190604_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
