# Generated by Django 2.0 on 2019-06-04 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_auto_20190604_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_suspended',
        ),
    ]
