# Generated by Django 2.0 on 2019-06-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_remove_user_is_suspended'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='serve_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='wait_time',
            field=models.IntegerField(default=0),
        ),
    ]
