# Generated by Django 2.0 on 2019-06-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_user_energy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='sumcost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
