# Generated by Django 2.0 on 2019-06-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_auto_20190607_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='change_speed_times',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='change_temp_times',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
